apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bjlf4406e-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bjlf4406e-nodejs 
  name: bjlf4406e-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bjlf4406e-nodejs 
